baseFolder: /Users/toni.navarro/NAS/Vault3D/
patreons:
  - Archvillain Games
  - Artisans Guild
  - Asgard Rising
  - Bite The Bullet
  - Last Sword Miniatures
  - Loot Studios
  - Titan Forge
  - Ritual Casting
