baseFolder: /Users/toni.navarro/NAS/Vault3D/
patreons:
  - Archvillain Games
  - Artisans Guild
  - Asgard Rising
  - Bite The Bullet
  - Last Sword Miniatures
  - Loot Studios
  - Red Dawn Miniatures
  - Ritual Casting
  - Signum Workshop
  - stepanovsculpts
  - STL Miniatures
  - Titan Forge
  - The Printing Goes Ever On
  - Twin Goddess
  - Warploque Miniatures
  - White Werewolf Tavern
