#!/usr/bin/env python3
import argparse
import os
import subprocess
import textwrap


# For each subfolder in current folder, repack all content as .7z
# For each individual file in current folder, if it is an STL or OBJ, also pack as indiviual 7z
# Settings for maximum compression
# Extra for OSX - dot_clean to remove .fu extra file
# Extra for OSX - At 7za, -xr to remove unwanted files: .DS_Store, Thumbs.db

def safe_execute(command):
    try:
        result = subprocess.run(command, shell=True, check=True)
    except subprocess.CalledProcessError:
        print("--- ERROR ---")
        exit(1)


def pack_folder(folder):
    safe_execute('7za a -t7z -m0=lzma2 -mx=9 -mqs=on -mfb=64 -md=1024m -ms=on ' +
                 '-xr!.DS_Store -xr!Thumbs.db -xr!desktop.ini ' +
                 '"' + folder + '.7z" "' + folder + '/"')
    safe_execute('rm -r "' + folder + '"')


def pack_file(file):
    name, extension = os.path.splitext(file)
    if extension.lower() in (".stl", ".obj"):
        safe_execute('7za a -t7z -m0=lzma2 -mx=9 -mqs=on -mfb=64 -md=1024m -ms=on ' +
                     '"' + name + '.7z" "' + file + '"')
        os.remove(file)


def clean_folder(folder):
    safe_execute('dot_clean "' + folder + '"')
    safe_execute('find "' + folder + '" \( -name ".DS_Store" -or -name "Thumbs.db" -or -name "desktop.ini" \) -delete ')


def pack_all():
    for entry in os.scandir("."):
        if entry.is_dir():
            pack_folder(entry.name)
        elif entry.is_file():
            pack_file(entry.name)


parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description=textwrap.dedent('''\
    STLHoarders Pack.
        Compress directories and files as 7z optimized files.
        If a target file or folder is provided, Pack will process it into a single 7z.
        If no target is provided, Pack will process all contents in current folder into individual 7z.
    '''))
parser.add_argument('target', type=str, nargs='?', help='Folder or file to pack.')
parser.add_argument('--sound', help="Say a voice warning once the process is finished", action="store_true")
args = parser.parse_args()


if args.target is None:
    clean_folder(".")
    pack_all()
else:
    if os.path.exists(args.target):
        if os.path.isdir(args.target):
            clean_folder(args.target)
            pack_folder(args.target)
        else:
            pack_file(args.target)
    else:
        print("Target", args.target, "does not exist")

if args.sound:
    safe_execute('say -v Monica "Pack completado"')
