#!/usr/bin/env python3
import os
import subprocess


# Unpack
# Extract RAR, ZIP and 7z files, and remove them
# Take care of NOT creating unnecessary nested dirs

def safe_execute(command):
    try:
        result = subprocess.run(command, shell=True, check=True)
    except subprocess.CalledProcessError:
        print("--- ERROR ---")
        exit(1)


def fix_double_folder(name):
    # We always force the creation of a folder... just to avoid spitting out files directly to current folder
    # But most times the packed file already included a folder... so we can end with unnecessary nesting
    if os.path.exists(name + "/" + name):
        os.rename(name, name + "_DELETE")
        os.rename(name + "_DELETE/" + name, name)
        safe_execute('rm -r "' + name + '_DELETE"')


for entry in os.scandir("."):
    if entry.is_file():
        name, extension = os.path.splitext(entry.name)
        if extension.lower() in (".rar", ".zip", ".7z"):
            print("Unpacking", entry.name)
            os.mkdir(name)
            if extension.lower() == ".rar":
                # Rar5 is not supported by 7z
                safe_execute('unrar x "' + entry.name + '" "' + name + '"')
            else:
                safe_execute('7z x "' + entry.name + '" -o"' + name + '"')
            fix_double_folder(name)
            os.remove(entry.path)

safe_execute('say -v Monica "Unpack completado"')
